version: "3.7"

services: 
  # openligo-dev:
  #   build: .
  #   ports:
  #     - 3000:3000
    # volumes:
    #   - ./:/app
    # command: npm run dev
  # openligo:
  #   build: .
  #   ports:
  #     - 3000:3000
  openlingo-database:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    env_file:
      - .env
    container_name: openlingo-database